import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <Navbar/>
        <section 
              className="relative min-h-screen bg-size-[1000px] bg-repeat "
              style={{ 
                backgroundImage: `
                  linear-gradient(rgba(255, 255, 255, 0.93), rgba(255, 255, 255, 0.93)),
                  url('/bg.png')
                `
              }}>
        {children}
        </section>
        <Footer/>
      </body>
    </html>
  );
}